演示程序中遇到的不懂的代码

In [ ]:
import numpy as np

如下代码的结果为-1 或者1,np.random.choice(2)在这里功能上相当于选择np.arange(2)里面的一个值

In [21]:
np.random.choice(2)*2 - 1

-1

In [22]:
np.arange(2)

array([0, 1])

In [23]:
x = np.arange(4).reshape((2,2))
print(x)

[[0 1]
 [2 3]]


np.transpose()的功能是转置一个array

In [24]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [4]:
import scipy.misc

ModuleNotFoundError: No module named 'scipy'

In [2]:
scipy.misc.imread('testdata/012.jpg')

NameError: name 'scipy' is not defined

如下演示高维numpy数组的tranpose转置

In [4]:
import numpy as np
t = np.arange(1,17).reshape(2,2,4)
print(t)
t1 = t.transpose(1,0,2)
print(t1)



[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [13 14 15 16]]]
[[[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]

 [[ 4  8]
  [12 16]]]


In [5]:
t = np.arange(1,13).reshape(2,2)
print(t)

t1 = t.transpose(2,0,1)
print(t1)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[ 2  4]
  [ 6  8]
  [10 12]]]
